# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 020409880383273aa78f62c146c559a93bbac04fcc258c8cd06c0834082dfe579d543a95f8ed267292a2e9fbbba40ad523c03305610c12b68ab55f7babba0226

test:
  secret_key_base: 3c3395ac0535507e8d8260f35629e06e52f9fea0081ce66f5ca6785ba669c7e9224fbba712017008e323a56dabefa4be684bc05bb3421c9316e5c762a05ede69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
